export default {
  ADD_POST: 'ADD_POST',
  REMOVE_ALL: 'REMOVE_ALL',
  REMOVE_POST: 'REMOVE_POST',
  PLUS_LIKE_COUNT: 'PLUS_LIKE_COUNT',
  MINUS_LIKE_COUNT: 'MINUS_LIKE_COUNT',
  CHANGE_POST: 'CHANGE_POST'
};
